In [2]:
import pandas as pd

In [9]:
rest_menus = pd.read_csv("total.tsv", sep='\t')

In [52]:
rest_menus

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
0,0,7 Delicatessen,Entrante,Ensalada de queso de cabra con naranja agria a...,"8,5 €",ensalada de queso de cabra con naranja agria a...,entrante
1,1,7 Delicatessen,Entrante,Tortilla de patata con cebolla caramelizada,8 €,tortilla de patata con cebolla caramelizada,entrante
2,2,7 Delicatessen,Entrante,Ensalada de foie y cebolla caramelizada,"8,5 €",ensalada de foie y cebolla caramelizada,entrante
3,3,7 Delicatessen,Plato,Pollo yakitori,8 €,pollo yakitori,plato
4,4,7 Delicatessen,Plato,Pizza de gambón y chile confitado,"8,5 €",pizza de gambón y chile confitado,plato
...,...,...,...,...,...,...,...
800,12,tuk tuk,seccion_bebidas,Botella de vino,14 €,botella de vino,seccion_bebidas
801,13,tuk tuk,seccion_bebidas,Copa de vino,"3,5 €",copa de vino,seccion_bebidas
802,0,Vides,Entrante,Ajo campero con puntillitas,NaN,ajo campero con puntillitas,entrante
803,1,Vides,Plato,Solomillo de Cerdo sobre Crema de Boniato con ...,NaN,solomillo de cerdo sobre crema de boniato con ...,plato
804,2,Vides,Postre,Tarta de chocolate,NaN,tarta de chocolate,postre

In [29]:
rest_menus.seccion.value_counts().head(50)

seccion_bebidas                        97
Postre                                 50
Entrante                               40
Plato                                  35
Postres                                33
Entrantes                              31
Comida Coreana                         26
Sushi Nigiri                           26
Fish Corner                            18
MENU                                   18
ENTRANTES FRIOS                        16
ENTRANTES CALIENTES                    16
Uramakis                               14
Sashimi                                12
ENTRANTES                              12
YOURSELF (Todos caseros)               11
Carnes                                 11
Nori Makis                             10
Tallarines                             10
Pizzas                                 10
Tapas                                   9
Recetas del Chef                        9
Compartir... o no?                      9
CARNES                                  9
Para entrar con buen pie                8
ARROCES Y PAELLAS                       8
Carnes con carácter...                  8
Arroces                                 8
Excepcional                             8
Ensaladas                               8
Tacos Típicos                           8
Nuestras Pastas y Arroces               7
Platos chicos                           7
PESCADOS                                7
Platos                                  7
Nuestros Entrantes                      7
Carne y Pescado                         6
SELF FISH                               6
Las tapas del BAZAAR para compartir     6
Nuestros Segundos                       6
Grill                                   6
Temakis                                 6
Nuestros Postres                        6
Sugerencia maldeamores                  6
Sabor a Mar                             6
Tempuras                                6
Platos grandes                          6
Productos del mar...                    5
Entre panes                             5
ENSALDADAS                              5
Name: seccion, dtype: int64

In [30]:
rest_menus.seccion.value_counts().tail(40)

Platos grandes                       6
Productos del mar...                 5
Entre panes                          5
ENSALDADAS                           5
Uno x Uno                            5
Pastas                               5
Para empezar                         5
SELF MEAT                            5
Trastapeando Granja                  4
Ensaladas - Zona Fresh :)            4
Sopas & Ensaladas                    4
Nuestras pastas y arroces            4
Trastapeando Mar                     4
Pizza y Pasta                        4
PETISCOS                             4
GALICIA EN 3 PLATOS                  3
Carpaccio                            3
POSTRE                               3
Para compartir                       3
GRANJA GALEGA                        3
PLATOS POR ENCARGO                   3
Tacos con Queso                      3
Trastapeando Huertas                 3
LONJA CORUÑESA                       3
Bowls                                2
Helados                              2
Risottos                             2
Pescados                             2
Tacos para los que no comen carne    2
CREMAS                               2
Sopas                                2
POSTRES CASEROS                      2
Para seguir comiendo...              2
Ensalada                             2
Mesas                                1
Golosos de la trastienda             1
Especiallidad maldeamores            1
*Reserva de 1 hora y media*          1
Servicio                             1
Aperitivo                            1
Name: seccion, dtype: int64

In [72]:
rest_menus[(rest_menus['restaurante']== 'Bosco de Lobos') |(rest_menus['restaurante']== 'Morgana') ]

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
126,0,Bosco de Lobos,Tapas,Croquetas de berenjena y parmigiano (6 unidades),6 €,croquetas de berenjena y parmigiano (6 unidades),tapas
127,1,Bosco de Lobos,Tapas,"Focaccia de stracchino, prosciutto di parma, r...",8 €,"focaccia de stracchino, prosciutto di parma, r...",tapas
128,2,Bosco de Lobos,Tapas,"Mejillones con hierbas, tomate cherry, Martini...",9 €,"mejillones con hierbas, tomate cherry, martini...",tapas
129,3,Bosco de Lobos,Tapas,Alcachofas fritas,7 €,alcachofas fritas,tapas
130,4,Bosco de Lobos,Tapas,Patatas Buthan (patatas bravas del Himalaya),8 €,patatas buthan (patatas bravas del himalaya),tapas
131,5,Bosco de Lobos,Tapas,"Tortitas de maíz, sashimi de atún y mayonesa d...",11 €,"tortitas de maíz, sashimi de atún y mayonesa d...",tapas
132,6,Bosco de Lobos,Tapas,Ceviche de pescado blanco con ají amarillo. na...,10 €,ceviche de pescado blanco con ají amarillo. na...,tapas
133,7,Bosco de Lobos,Tapas,Fritura de calamar y lima,12 €,fritura de calamar y lima,tapas
134,8,Bosco de Lobos,Tapas,Canelón de espinacas con pasas y piñones,7 €,canelón de espinacas con pasas y piñones,tapas
135,9,Bosco de Lobos,Sopas & Ensaladas,Ensalada templada de quinoa con verduras cruji...,11 €,ensalada templada de quinoa con verduras cruji...,sopas & ensaladas
136,10,Bosco de Lobos,Sopas & Ensaladas,Ensalada de burrata con berenjena ahumada,12 €,ensalada de burrata con berenjena ahumada,sopas & ensaladas
137,11,Bosco de Lobos,Sopas & Ensaladas,Cogollos templados a la bagnacauda (salsa de a...,8 €,cogollos templados a la bagnacauda (salsa de a...,sopas & ensaladas
138,12,Bosco de Lobos,Sopas & Ensaladas,Ensalada de pimientos asados con atún confitad...,11 €,ensalada de pimientos asados con atún confitad...,sopas & ensaladas
139,13,Bosco de Lobos,Carpaccio,Carpaccio clásico de ternera con salsa cipriani,13 €,carpaccio clásico de ternera con salsa cipriani,carpaccio
140,14,Bosco de Lobos,Carpaccio,Carpaccio de pescado blanco con salsa oriental...,12 €,carpaccio de pescado blanco con salsa oriental...,carpaccio
141,15,Bosco de Lobos,Carpaccio,Tartar de atún con cítricos,14 €,tartar de atún con cítricos,carpaccio
142,16,Bosco de Lobos,Pizzas,Verduas a la brasa con masa de harina integral,13 €,verduas a la brasa con masa de harina integral,pizzas
143,17,Bosco de Lobos,Pizzas,Margherita,10 €,margherita,pizzas
144,18,Bosco de Lobos,Pizzas,"Porchetta, berenjena con salsa de miel y mostaza",13 €,"porchetta, berenjena con salsa de miel y mostaza",pizzas
145,19,Bosco de Lobos,Pizzas,"Marinara (sin queso, con anchoas y alcaparras)",13 €,"marinara (sin queso, con anchoas y alcaparras)",pizzas
146,20,Bosco de Lobos,Pizzas,Calzone cotto e funghi,12 €,calzone cotto e funghi,pizzas
147,21,Bosco de Lobos,Pizzas,"Ricotta, anchoas y flor de calabacín",14 €,"ricotta, anchoas y flor de calabacín",pizzas
148,22,Bosco de Lobos,Pizzas,Pizza de panceta y espárragos,12 €,pizza de panceta y espárragos,pizzas
149,23,Bosco de Lobos,Pastas,Lasagna clásica bolognesa,11 €,lasagna clásica bolognesa,pastas
150,24,Bosco de Lobos,Pastas,Pappardelle con ragú de carne al vino tinto,12 €,pappardelle con ragú de carne al vino tinto,pastas
151,25,Bosco de Lobos,Pastas,Pappardelle al nero di sepia,13 €,pappardelle al nero di sepia,pastas
152,26,Bosco de Lobos,Pastas,Spaghetti carbonara,13 €,spaghetti carbonara,pastas
153,27,Bosco de Lobos,Pastas,Spaghetti vongole (tomates cherry y almejas),14 €,spaghetti vongole (tomates cherry y almejas),pastas
154,28,Bosco de Lobos,Risottos,Setas de temporada (20 min),17 €,setas de temporada (20 min),risottos
155,29,Bosco de Lobos,Risottos,Caldo de cigala con su carpaccio (20 min),18 €,caldo de cigala con su carpaccio (20 min),risottos
156,30,Bosco de Lobos,Carne y Pescado,Tagliata de ternera con patata rústica,19 €,tagliata de ternera con patata rústica,carne y pescado
157,31,Bosco de Lobos,Carne y Pescado,"Hamburguesa Bosco con pesto, tomate seco y pat...",11 €,"hamburguesa bosco con pesto, tomate seco y pat...",carne y pescado
158,32,Bosco de Lobos,Carne y Pescado,Streak Tartar con salsa de estragón y verduritas,18 €,streak tartar con salsa de estragón y verduritas,carne y pescado
159,33,Bosco de Lobos,Carne y Pescado,Pollo entero a la brasa con puré de patata y p...,16 €,pollo entero a la brasa con puré de patata y p...,carne y pescado
160,34,Bosco de Lobos,Carne y Pescado,Bonito con cremoso de patata y setas,16 €,bonito con cremoso de patata y setas,carne y pescado
161,35,Bosco de Lobos,Carne y Pescado,Merluza al horno con gratén de hinojo,16 €,merluza al horno con gratén de hinojo,carne y pescado
472,0,Morgana,PETISCOS,TOMATES MARINADOS IIIª PARTE,"10,5 €",tomates marinados iiiª parte,petiscos
473,1,Morgana,PETISCOS,TOSTA DE SARDINA AHUMADA,12 €,tosta de sardina ahumada,petiscos
474,2,Morgana,PETISCOS,VIEIRA MEX,14 €,vieira mex,petiscos
475,3,Morgana,PETISCOS,CROQUETAS CASERAS,9 €,croquetas caseras,petiscos
476,4,Morgana,GALICIA EN 3 PLATOS,EMPANADA artesana del día,8 €,empanada artesana del día,galicia en 3 platos
477,5,Morgana,GALICIA EN 3 PLATOS,TORTILLA,9 €,tortilla,galicia en 3 platos
478,6,Morgana,GALICIA EN 3 PLATOS,FILLOA DE COCIDO y emulsión de grel,12 €,filloa de cocido y emulsión de grel,galicia en 3 platos
479,7,Morgana,LONJA CORUÑESA,MERLUZA DEL PINCHO a baja temperatura,19 €,merluza del pincho a baja temperatura,lonja coruñesa
480,8,Morgana,LONJA CORUÑESA,PULPO A LA PLANCHA,20 €,pulpo a la plancha,lonja coruñesa
481,9,Morgana,LONJA CORUÑESA,MEJILLÓN TOM KHA GA,16 €,mejillón tom kha ga,lonja coruñesa
482,10,Morgana,GRANJA GALEGA,RABO DE VACA DESMECHADA,"17,5 €",rabo de vaca desmechada,granja galega
483,11,Morgana,GRANJA GALEGA,CROCA ROXA D’OURO,19 €,croca roxa d’ouro,granja galega
484,12,Morgana,GRANJA GALEGA,PICANHA RUBIA GALLEGA (45 días maduración),"17,5 €",picanha rubia gallega (45 días maduración),granja galega
485,13,Morgana,POSTRE,LA TARTA DE QUESO DE MORGANA,6 €,la tarta de queso de morgana,postre
486,14,Morgana,POSTRE,CAÑITAS DO CARBALLIÑO,6 €,cañitas do carballiño,postre
487,15,Morgana,POSTRE,CHOCOLATE,"6,5 €",chocolate,postre

In [70]:
rest_menus[(rest_menus['seccion']== 'Carpaccio') |(rest_menus['seccion']== 'POSTRE') ]

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
139,13,Bosco de Lobos,Carpaccio,Carpaccio clásico de ternera con salsa cipriani,13 €,carpaccio clásico de ternera con salsa cipriani,carpaccio
140,14,Bosco de Lobos,Carpaccio,Carpaccio de pescado blanco con salsa oriental...,12 €,carpaccio de pescado blanco con salsa oriental...,carpaccio
141,15,Bosco de Lobos,Carpaccio,Tartar de atún con cítricos,14 €,tartar de atún con cítricos,carpaccio
485,13,Morgana,POSTRE,LA TARTA DE QUESO DE MORGANA,6 €,la tarta de queso de morgana,postre
486,14,Morgana,POSTRE,CAÑITAS DO CARBALLIÑO,6 €,cañitas do carballiño,postre
487,15,Morgana,POSTRE,CHOCOLATE,"6,5 €",chocolate,postre

In [ ]:
mask1 = (rest_menus['seccion'] == 'seccion_bebidas')
mask2 = (rest_menus['seccion']== 'Aperitivo')
mask3 = (rest_menus['seccion']== '*Reserva de 1 hora y media*')
mask4 = (rest_menus['seccion']== 'Servicio')
mask5 = (rest_menus['seccion']== 'Golosos de la trastienda')
mask6 = (rest_menus['seccion']== 'Mesas')
mask7 = (rest_menus['seccion']== 'POSTRES CASEROS')
mask8 = (rest_menus['seccion']== 'Tacos para los que no comen carne')

In [53]:
# Elimino las bebidas
rest_menu1 = rest_menus[~((rest_menus['seccion'] == 'seccion_bebidas')|(rest_menus['seccion']== 'Aperitivo') |(rest_menus['seccion']== '*Reserva de 1 hora y media*') | (rest_menus['seccion']== 'Servicio') | (rest_menus['seccion']== 'Golosos de la trastienda') | (rest_menus['seccion']== 'Mesas'))]

In [31]:
rest_menus[(rest_menus['seccion']== 'Aperitivo') |(rest_menus['seccion']== 'Servicio') ]

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
357,20,Kuoco 360,Aperitivo,Pan de masa madre y aperitivo,"2,5 €",pan de masa madre y aperitivo,aperitivo
373,1,La Trastienda,Servicio,Servicio de pan y cubiertos,"1,5 €",servicio de pan y cubiertos,servicio

In [44]:
rest_menus[(rest_menus['seccion']== 'Mesas') |(rest_menus['seccion']== 'Golosos de la trastienda') ]

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
0,0,7 Delicatessen,Entrante,Ensalada de queso de cabra con naranja agria a...,"8,5 €",ensalada de queso de cabra con naranja agria a...,entrante
1,1,7 Delicatessen,Entrante,Tortilla de patata con cebolla caramelizada,8 €,tortilla de patata con cebolla caramelizada,entrante
2,2,7 Delicatessen,Entrante,Ensalada de foie y cebolla caramelizada,"8,5 €",ensalada de foie y cebolla caramelizada,entrante
3,3,7 Delicatessen,Plato,Pollo yakitori,8 €,pollo yakitori,plato
4,4,7 Delicatessen,Plato,Pizza de gambón y chile confitado,"8,5 €",pizza de gambón y chile confitado,plato
...,...,...,...,...,...,...,...
800,12,tuk tuk,seccion_bebidas,Botella de vino,14 €,botella de vino,seccion_bebidas
801,13,tuk tuk,seccion_bebidas,Copa de vino,"3,5 €",copa de vino,seccion_bebidas
802,0,Vides,Entrante,Ajo campero con puntillitas,NaN,ajo campero con puntillitas,entrante
803,1,Vides,Plato,Solomillo de Cerdo sobre Crema de Boniato con ...,NaN,solomillo de cerdo sobre crema de boniato con ...,plato
804,2,Vides,Postre,Tarta de chocolate,NaN,tarta de chocolate,postre

In [80]:
rest_menus.restaurante.unique()

array(['7 Delicatessen', 'Aloha Poké', 'Bagatella', 'Bazaar', 'Boho Bar',
       'Bosco de Lobos', 'Dionisos', 'Food Truck', 'Gioia Restaurante',
       'Hamburguesa Nostra', 'Hot Now', 'Izakaya Han', 'Kuoco 360',
       'La Carmencita', 'La Trastienda', 'le cocó', 'Mal de Amores',
       'Morgana', 'Restaurante Arce', 'RESTAURANTE KRITIKOS', 'Roostiq',
       'San Wich', 'Sr. Ito', 'Taberna El Buo', 'Tepic', 'TE CATO',
       'tuk tuk', 'Vides'], dtype=object)

In [125]:
rest_menus[(rest_menus['restaurante']== 'Bazaar')]

,Unnamed: 0,restaurante,seccion,platos,precios,platos_lower,seccion_lower
39,0,Bazaar,Las tapas del BAZAAR para compartir,Berenjenas crujientes a la miel y soja,"5,9 €",berenjenas crujientes a la miel y soja,las tapas del bazaar para compartir
40,1,Bazaar,Las tapas del BAZAAR para compartir,Croquetas cremosas de chipirones con su tinta,"7,95 €",croquetas cremosas de chipirones con su tinta,las tapas del bazaar para compartir
41,2,Bazaar,Las tapas del BAZAAR para compartir,Gyozas de verduras con kimchie de fresas y col...,"6,95 €",gyozas de verduras con kimchie de fresas y col...,las tapas del bazaar para compartir
42,3,Bazaar,Las tapas del BAZAAR para compartir,Croquetas de setas de temporada,"7,75 €",croquetas de setas de temporada,las tapas del bazaar para compartir
43,4,Bazaar,Las tapas del BAZAAR para compartir,Tartar de atún estilo Bazaar,"8,45 €",tartar de atún estilo bazaar,las tapas del bazaar para compartir
44,5,Bazaar,Las tapas del BAZAAR para compartir,Alcachofas blancas de Tudela con langostinos p...,"9,95 €",alcachofas blancas de tudela con langostinos p...,las tapas del bazaar para compartir
45,6,Bazaar,Para entrar con buen pie,Gazpacho andaluz con picatostes y veduritas,"5,95 €",gazpacho andaluz con picatostes y veduritas,para entrar con buen pie
46,7,Bazaar,Para entrar con buen pie,"Ensalada griega con queso feta, cous-cous, pan...","7,95 €","ensalada griega con queso feta, cous-cous, pan...",para entrar con buen pie
47,8,Bazaar,Para entrar con buen pie,"Ensalada con virutas de cabra, mango, granola ...","8,05 €","ensalada con virutas de cabra, mango, granola ...",para entrar con buen pie
48,9,Bazaar,Para entrar con buen pie,Mousse de foie con queso de cabra gratinado,"8,65 €",mousse de foie con queso de cabra gratinado,para entrar con buen pie
49,10,Bazaar,Para entrar con buen pie,Las tres ensaladas con queso fresco y piñones ...,"8,9 €",las tres ensaladas con queso fresco y piñones ...,para entrar con buen pie
50,11,Bazaar,Para entrar con buen pie,Ensalada de algas marinas con atún y sésamo,"8,95 €",ensalada de algas marinas con atún y sésamo,para entrar con buen pie
51,12,Bazaar,Para entrar con buen pie,Verdura a la plancha con romesco de nueces,"8,9 €",verdura a la plancha con romesco de nueces,para entrar con buen pie
52,13,Bazaar,Para entrar con buen pie,Nuestra ensalada especial de huevo pochê con b...,"8,95 €",nuestra ensalada especial de huevo pochê con b...,para entrar con buen pie
53,14,Bazaar,Nuestras pastas y arroces,Macarrones con boloñesa vegana Coreana de shit...,"7,85 €",macarrones con boloñesa vegana coreana de shit...,nuestras pastas y arroces
54,15,Bazaar,Nuestras pastas y arroces,"Yakisoba de calamar, gambitas, verduras wok y ...","9,85 €","yakisoba de calamar, gambitas, verduras wok y ...",nuestras pastas y arroces
55,16,Bazaar,Nuestras pastas y arroces,Spaghetti con salsa de gambas picante,"8,85 €",spaghetti con salsa de gambas picante,nuestras pastas y arroces
56,17,Bazaar,Nuestras pastas y arroces,Risotto de setas con queso parmesano,"9,35 €",risotto de setas con queso parmesano,nuestras pastas y arroces
57,18,Bazaar,Carnes con carácter...,Tiras de pollo crispie con dos salsas,"8,3 €",tiras de pollo crispie con dos salsas,carnes con carácter...
58,19,Bazaar,Carnes con carácter...,Pollo al curry con fideos sothangon,"9,9 €",pollo al curry con fideos sothangon,carnes con carácter...
59,20,Bazaar,Carnes con carácter...,Hamburguesa de ternera con camembert y cebolla...,"10,6 €",hamburguesa de ternera con camembert y cebolla...,carnes con carácter...
60,21,Bazaar,Carnes con carácter...,Canelón de carrillada de ternera al Pedro Ximénez,"11,15 €",canelón de carrillada de ternera al pedro ximénez,carnes con carácter...
61,22,Bazaar,Carnes con carácter...,"Lomo de ternera con salsa de vino, setas y par...","11,6 €","lomo de ternera con salsa de vino, setas y par...",carnes con carácter...
62,23,Bazaar,Carnes con carácter...,"Buey tierno con parmesano, rúcula, cebolla asa...","11,85 €","buey tierno con parmesano, rúcula, cebolla asa...",carnes con carácter...
63,24,Bazaar,Carnes con carácter...,Las tres carnes braseadas con fideos Thai,"11,95 €",las tres carnes braseadas con fideos thai,carnes con carácter...
64,25,Bazaar,Carnes con carácter...,Salsa a elegir: pimienta verde o quesos,1 €,salsa a elegir: pimienta verde o quesos,carnes con carácter...
65,26,Bazaar,Productos del mar...,Pulpitos encebollados sobre patatas confitadas,"10,95 €",pulpitos encebollados sobre patatas confitadas,productos del mar...
66,27,Bazaar,Productos del mar...,Bacalao gratinado con ali-oli de pera,"12,65 €",bacalao gratinado con ali-oli de pera,productos del mar...
67,28,Bazaar,Productos del mar...,"Tataki de atún con tartar de mango, tomate, ci...","11,85 €","tataki de atún con tartar de mango, tomate, ci...",productos del mar...
68,29,Bazaar,Productos del mar...,Salmón a la plancha con trompetas de los muert...,"12,9 €",salmón a la plancha con trompetas de los muert...,productos del mar...
69,30,Bazaar,Productos del mar...,Bacalao confitado con aceite de ajo y sepia,"12,85 €",bacalao confitado con aceite de ajo y sepia,productos del mar...
70,31,Bazaar,Postre,Mini fondue de chocolate con brochetas de frut...,"4,75 €",mini fondue de chocolate con brochetas de frut...,postre
71,32,Bazaar,Postre,Sorbete de limón (con cava +1€),"4,9 €",sorbete de limón (con cava +1€),postre
72,33,Bazaar,Postre,"Copa mango, mango y mas mango con lima crispie","5,5 €","copa mango, mango y mas mango con lima crispie",postre
73,34,Bazaar,Postre,Tarta al chocolate al estilo del señor Patubo,"4,6 €",tarta al chocolate al estilo del señor patubo,postre
74,35,Bazaar,Postre,Pastel de nueces con chocolate caliente,"4,95 €",pastel de nueces con chocolate caliente,postre
75,36,Bazaar,Postre,Tarta Sacher con chocolate caliente,"5,35 €",tarta sacher con chocolate caliente,postre
76,37,Bazaar,Postre,Los íssimos del Bazaar,"5,1 €",los íssimos del bazaar,postre
77,38,Bazaar,Postre,Tarta de mascarpone con fresas y helado de cacao,"5,25 €",tarta de mascarpone con fresas y helado de cacao,postre
78,39,Bazaar,Postre,Tarta de queso al coulis de fruta,"5,35 €",tarta de queso al coulis de fruta,postre
79,40,Bazaar,Postre,Chocolatísimo,"5,2 €",chocolatísimo,postre
80,41,Bazaar,seccion_bebidas,Café,2 €,café,seccion_bebidas
81,42,Bazaar,seccion_bebidas,Media botella de agua,"2,2 €",media botella de agua,seccion_bebidas
82,43,Bazaar,seccion_bebidas,Botella de vino,14 €,botella de vino,seccion_bebidas
83,44,Bazaar,seccion_bebidas,Copa de vino,"2,5 €",copa de vino,seccion_bebidas

In [129]:
estilo_restaurante =['Canarias', 'Hawai: pokes, gazpacho, hummus', 'Mediterranea, peruana, ecológica', 'Mediterránea con toque oriental', 'Mediterranea: ensaldas, pizzas, carnes, pescado', 'Italiano y algo mas', 'Griego', 'Americano', 'Italiano', 'Italiano', 'Pizza, guacamole, Hummus', 'Japonés', 'Asiatico latino español', 'Español', 'Español, raciones y paellas', 'Mediterraneo, Perú, NY, Tokio', 'Español sin paella', 'Gallego', 'Español sin paella', 'Griego', 'Español con paellas, pescado y carne y algo más','Hamburguesa, sandwich y gazpacho', 'Japonés', 'Español sin paella', 'Mexicano', 'variado pero sin precios', 'Asian street food', 'Sin precios'    ]

In [130]:
rest_style = pd.DataFrame({'restaurante':['7 Delicatessen', 'Aloha Poké', 'Bagatella', 'Bazaar', 'Boho Bar',
       'Bosco de Lobos', 'Dionisos', 'Food Truck', 'Gioia Restaurante',
       'Hamburguesa Nostra', 'Hot Now', 'Izakaya Han', 'Kuoco 360',
       'La Carmencita', 'La Trastienda', 'le cocó', 'Mal de Amores',
       'Morgana', 'Restaurante Arce', 'RESTAURANTE KRITIKOS', 'Roostiq',
       'San Wich', 'Sr. Ito', 'Taberna El Buo', 'Tepic', 'TE CATO',
       'tuk tuk', 'Vides'], 'Cocina': estilo_restaurante},
       columns= ['restaurante', 'Cocina'])
rest_style

             restaurante                                           Cocina
0         7 Delicatessen                                         Canarias
1             Aloha Poké                   Hawai: pokes, gazpacho, hummus
2              Bagatella                 Mediterranea, peruana, ecológica
3                 Bazaar                  Mediterránea con toque oriental
4               Boho Bar  Mediterranea: ensaldas, pizzas, carnes, pescado
5         Bosco de Lobos                              Italiano y algo mas
6               Dionisos                                           Griego
7             Food Truck                                        Americano
8      Gioia Restaurante                                         Italiano
9     Hamburguesa Nostra                                         Italiano
10               Hot Now                         Pizza, guacamole, Hummus
11           Izakaya Han                                          Japonés
12             Kuoco 360                          Asiatico latino español
13         La Carmencita                                          Español
14         La Trastienda                      Español, raciones y paellas
15               le cocó                    Mediterraneo, Perú, NY, Tokio
16         Mal de Amores                               Español sin paella
17               Morgana                                          Gallego
18      Restaurante Arce                               Español sin paella
19  RESTAURANTE KRITIKOS                                           Griego
20               Roostiq  Español con paellas, pescado y carne y algo más
21              San Wich                 Hamburguesa, sandwich y gazpacho
22               Sr. Ito                                          Japonés
23        Taberna El Buo                               Español sin paella
24                 Tepic                                         Mexicano
25               TE CATO                         variado pero sin precios
26               tuk tuk                                Asian street food
27                 Vides                                      Sin precios

In [132]:
rest_style = pd.DataFrame({'restaurante':rest_menus.restaurante.unique(), 'Cocina': estilo_restaurante},
       columns= ['restaurante', 'Cocina'])
rest_style

             restaurante                                           Cocina
0         7 Delicatessen                                         Canarias
1             Aloha Poké                   Hawai: pokes, gazpacho, hummus
2              Bagatella                 Mediterranea, peruana, ecológica
3                 Bazaar                  Mediterránea con toque oriental
4               Boho Bar  Mediterranea: ensaldas, pizzas, carnes, pescado
5         Bosco de Lobos                              Italiano y algo mas
6               Dionisos                                           Griego
7             Food Truck                                        Americano
8      Gioia Restaurante                                         Italiano
9     Hamburguesa Nostra                                         Italiano
10               Hot Now                         Pizza, guacamole, Hummus
11           Izakaya Han                                          Japonés
12             Kuoco 360                          Asiatico latino español
13         La Carmencita                                          Español
14         La Trastienda                      Español, raciones y paellas
15               le cocó                    Mediterraneo, Perú, NY, Tokio
16         Mal de Amores                               Español sin paella
17               Morgana                                          Gallego
18      Restaurante Arce                               Español sin paella
19  RESTAURANTE KRITIKOS                                           Griego
20               Roostiq  Español con paellas, pescado y carne y algo más
21              San Wich                 Hamburguesa, sandwich y gazpacho
22               Sr. Ito                                          Japonés
23        Taberna El Buo                               Español sin paella
24                 Tepic                                         Mexicano
25               TE CATO                         variado pero sin precios
26               tuk tuk                                Asian street food
27                 Vides                                      Sin precios

In [ ]:
rest_style.to_csv ('rest_style.csv')